name: trainer
sha1: 445712c757ef3e0a52733ffbcf743295e49f34f6
options:
  basename: trainer.us
  target_path: ../fs/us/trainer.bin
  base_path: .
  compiler: SN64
  find_file_boundaries: True
  do_c_func_detection: yes
  migrate_rodata_to_functions: yes
  # header_encoding: ASCII
  platform: n64
  create_undefined_funcs_auto: False
  # undefined_funcs_auto_path: undefined_funcs_us.txt
  create_undefined_syms_auto: False
  # undefined_syms_auto_path: undefined_syms_us.txt
  symbol_addrs_path: symbol_addrs_us.txt
  # asm_path: asm
  # src_path: src
  # build_path: build
  extensions_path: ../tools/splat_ext
  # mips_abi_float_regs: o32
  section_order: [".text", ".data", ".rodata", ".bss"]
  auto_all_sections: [".data", ".rodata", ".bss"]
  libultra_symbols: True
  hardware_regs: True
  asset_path: assets/us/
  asm_path: src/
  nonmatchings_path: ../asm/us/nonmatchings/
  build_path: build/us/
  disasm_unknown: True
  asm_emit_size_directive: false
  # generated_s_preamble:
    # .include "macro.inc"

    # .set noat

    # .set noreorder

segments:
  - name: main
    type: code
    start: 0x0
    vram: 0x80780800
    subsegments:
      - [0x0, c, main]
      - [0x450, c]
      - [0xAE0, hasm]
      - [0xC40, c]
      - [0xF80, c]
      - [0x5390, c]
      - [0x5960, c]
      - [0x7780, c, hw]
      - [0x7850, c]
      - [0xF8E0, c]
      - [0x14280, gsasm]
      - [0x145C0, bin]
  
  - name: fsblob
    type: fsblob
    out_dir: fs/us/
    start: 0x151B0
    follows_vram: main
  
  - name: data
    type: bin
    start: 0x194F0
    follows_vram: fsblob
      
  - [0x19948]
  
  